# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bss',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rodata',
            options={'ordering': ['-name']},
        ),
    ]
