# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_auto_20170416_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arg',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='constant',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='rodata',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='stack',
            options={'ordering': ['id']},
        ),
    ]
