# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_auto_20170416_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['id']},
        ),
    ]
